name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Rust Cache
      uses: actions/cache@v4.1.2
      with:
        key: 'rust'
        path: 'src-tauri/target/**'
    - name: Setup Node v22
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2.0.10
      with:
        api-level: 31
        build-tools: 31.0.0
        ndk: 23.1.7779620
    - run: echo "NDK_HOME=$ANDROID_NDK_HOME" >> $GITHUB_ENV  
    - name: Install npm deps
      run: npm i
    - name: Setup Rust targets
      run: rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android
    - name: Start build
      env:
        NDK_HOME: ${{ env.NDK_HOME }}
      run: npm run tauri android build