name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Rust Cache
      uses: actions/cache@v4.1.2
      with:
        key: 'android-rust'
        path: 'src-tauri/target/**'
    - name: Setup Node v22
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2.0.10
      with:
        api-level: 31
        build-tools: 31.0.0
        ndk: 23.1.7779620
    - run: echo "NDK_HOME=$ANDROID_NDK_HOME" >> $GITHUB_ENV  
    - name: Install npm deps
      run: npm i
    - name: Setup Rust targets
      run: rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android
    - name: Setup Android Signing
      run: |
        cd src-tauri/gen/android
        echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" > keystore.properties
        echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> keystore.properties
        echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> keystore.properties
        base64 -d <<< "${{ secrets.ANDROID_KEY_BASE64 }}" > $RUNNER_TEMP/keystore.jks
        echo "storeFile=$RUNNER_TEMP/keystore.jks" >> keystore.properties
    - name: Build
      env:
        NDK_HOME: ${{ env.NDK_HOME }}
      run: npm run tauri android build
    - name: Download bundletool
      run: curl -L -o bundletool.jar https://github.com/google/bundletool/releases/download/1.15.0/bundletool-all-1.15.0.jar
    - name: Extract Universal APK
      run: |
        java -jar bundletool.jar build-apks \
          --bundle=src-tauri/gen/android/app/build/outputs/bundle/universalRelease/app-universal-release.aab \
          --output=output.apks \
          --mode=universal \
          --overwrite
        unzip -p output.apks universal.apk > app-universal.apk
    - name: Upload Universal APK
      uses: actions/upload-artifact@v3
      with:
        name: app-universal.apk
        path: app-universal.apk
